Repository GSG-G11/Fitness-house, pull requests merged in 2022-05, with the labels that each got.

#23 Create fake data
  .eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  example.env
  package.json
  server/app.ts
  server/database/config/build.ts
  server/database/config/connection.ts
  server/database/fakeData/gyms.json
  server/database/fakeData/images.json
  server/database/fakeData/index.ts
  server/database/fakeData/reviews.json
  server/database/fakeData/subscriptions.json
  server/database/fakeData/users.json
  server/database/models/gyms.ts
  server/database/models/index.ts
  server/database/models/reviews.ts
  server/database/models/subscription.ts
  server/database/models/users.ts
  services/cities.json
  services/features.json
  tsconfig.json
Labels: Awaiting Review

#27 Create custom error for server
  server/utils/CustomError.ts
  server/utils/index.ts
Labels: Approved

#32 Create api for getting top gyms
  client/package.json
  example.env
  jest.config.ts
  package-lock.json
  package.json
  server/app.ts
  server/controllers/gyms/getTopGyms.ts
  server/controllers/gyms/index.ts
  server/controllers/index.ts
  server/database/config/build.sql
  server/database/fakeData/index.ts
  server/database/fakeData/reviews.json
  server/routes/gyms.ts
  server/routes/index.ts
  test/routes.test.js
  test/routes.test.ts
Labels: Done, BackEnd

#29 How to join Component
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Footer/index.jsx
  client/src/Components/Footer/style.css
  client/src/Components/Joinus/index.jsx
  client/src/Components/Joinus/style.css
  client/src/Pages/HomePage.jsx
  client/src/Pages/index.js
  client/src/app.css
  client/src/layouts/Home.jsx
Labels: Awaiting Review, FrontEnd

#38 Create Github Actions
  .github/workflows/node.js.yml
  client/src/App.js
Labels: Approved

#33 card component
  client/src/Components/Card/index.jsx
  client/src/Components/Card/style.css
  client/src/Components/Cards/index.jsx
  client/src/Components/Cards/style.css
  client/src/Pages/HomePage.jsx
  client/src/Theme.js
  client/src/app.css
Labels: Awaiting Review, FrontEnd

#36 Create Frontend what do we offer you component
  client/src/Components/OfferForYou/index.jsx
  client/src/Components/OfferForYou/style.css
  client/src/Layouts/Dashboard.jsx
  client/src/Layouts/Home.jsx
  client/src/Layouts/index.jsx
  client/src/Pages/HomePage.jsx
  client/src/app.css
Labels: Awaiting Review, FrontEnd

#41 Create Slider
  client/package-lock.json
  client/package.json
  client/src/Components/Footer/style.css
  client/src/Components/Joinus/style.css
  client/src/Components/Slider/Style.css
  client/src/Components/Slider/index.jsx
  client/src/Pages/HomePage.jsx
  tsconfig.json
Labels: Awaiting Review, FrontEnd

#45 Create Api For Gym Search
  client/src/Components/Card/index.jsx
  client/src/Components/Cards/index.jsx
  client/src/Pages/HomePage.jsx
  server/controllers/gyms/SerachGymByName.ts
  server/controllers/gyms/index.ts
  server/controllers/index.ts
  server/routes/gyms.ts
  server/utils/index.ts
  test/routes.test.ts
Labels: Awaiting Review, BackEnd

#42 Create api for getting gym data
  package.json
  server/controllers/gym/getGym.ts
  server/controllers/gym/index.ts
  server/controllers/gyms/getTopGyms.ts
  server/controllers/index.ts
  server/database/fakeData/gyms.json
  server/database/models/gyms.ts
  server/routes/gyms.ts
  server/utils/validation/index.ts
  server/utils/validation/paramsValidation.ts
  test/routes.test.ts
Labels: Awaiting Review, BackEnd

#50 Create gym profile main component
  client/src/Components/GymProfile/index.jsx
  client/src/Components/GymProfile/style.css
  client/src/Pages/ProfileGym.jsx
Labels: Awaiting Review, FrontEnd

#51 Fix config
  package.json
  tsconfig.json
Labels: Awaiting Review, BackEnd

#46 Front end get data form api and convert home page to be dynamic
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/Components/Card/index.jsx
  client/src/Components/Card/style.css
  client/src/Components/Cards/LoadingCard.jsx
  client/src/Components/Cards/index.jsx
  client/src/Components/Cards/style.css
  client/src/Components/Footer/index.jsx
  client/src/Components/Footer/style.css
  client/src/Components/Joinus/index.jsx
  client/src/Components/Joinus/style.css
  client/src/Components/OfferForYou/index.jsx
  client/src/Components/OfferForYou/style.css
  client/src/Components/Slider/Style.css
  client/src/Components/Slider/index.jsx
  client/src/Components/index.jsx
  client/src/Store/Services/TopGyms.js
  client/src/Store/index.js
  client/src/app.css
  client/src/index.js
  package.json
  test/routes.test.ts
Labels: Awaiting Review, FrontEnd

#52 Create review components
  client/src/Components/Reviews/Review.jsx
  client/src/Components/Reviews/index.jsx
  client/src/Components/Reviews/style.css
  client/src/Pages/ProfileGym.jsx
  server/controllers/gym/getGym.ts
Labels: Awaiting Review, FrontEnd

#57 Create Gym Images Component
  client/src/Components/GymImages/index.jsx
  client/src/Components/GymImages/style.css
  client/src/Components/GymProfile/index.jsx
  client/src/Components/GymProfile/style.css
  client/src/Pages/ProfileGym.jsx
Labels: Awaiting Review, FrontEnd

#58 Get data from API and convert the Gym page to be dynamic
  client/src/Components/Card/index.jsx
  client/src/Components/Cards/index.jsx
  client/src/Components/GymImages/index.jsx
  client/src/Components/GymImages/style.css
  client/src/Components/GymProfile/index.jsx
  client/src/Components/Reviews/Review.jsx
  client/src/Components/Reviews/index.jsx
  client/src/Components/Reviews/style.css
  client/src/Pages/HomePage.jsx
  client/src/Pages/ProfileGym.jsx
  client/src/Store/Services/gyms.js
  client/src/Store/index.js
  server/controllers/gym/getGym.ts
  server/database/fakeData/images.json
Labels: Approved, FrontEnd

#62 Frontend create a card for rendering the result of filtering
  client/src/Components/Footer/index.jsx
  client/src/Components/Footer/style.css
  client/src/Components/SearchPageComponents/CardResultFilter/Card.jsx
  client/src/Components/SearchPageComponents/CardResultFilter/index.jsx
  client/src/Components/SearchPageComponents/CardResultFilter/style.css
  client/src/Components/SearchPageComponents/Filter/index.jsx
  client/src/Components/SearchPageComponents/Filter/style.css
  client/src/Components/SearchPageComponents/index.js
  client/src/Components/index.js
  client/src/Layouts/index.js
  client/src/Pages/SearchGym.jsx
  package.json
Labels: Approved, FrontEnd

#61 Create Side Filter Component
  client/src/Components/FilterSide/index.jsx
  client/src/Components/FilterSide/style.css
  client/src/Pages/SearchGym.jsx
Labels: Done, FrontEnd

#65 FrontEnd Create Function to check users is auth and Store in Redux
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/GymImages/index.jsx
  client/src/Store/Slices/checkAuthSlice.js
  client/src/Store/Slices/index.js
  client/src/Store/index.js
Labels: Approved, FrontEnd

#68 Create user/gym auth
  package-lock.json
  package.json
  server/middleware/checkAuth.ts
  server/middleware/index.ts
  server/middlewares/index.ts
  server/utils/index.ts
  server/utils/jwt.ts
  server/utils/types.ts
Labels: Done, BackEnd

#70 Fix build database function to create data async
  .eslintrc.json
  server/database/fakeData/index.ts
Labels: Awaiting Review, BackEnd

#74 [backend] Upload Image
  package-lock.json
  package.json
  server/utils/types.ts
  server/utils/uplodeImage/index.ts
Labels: Approved, BackEnd

#73 Get start with configration stepper
  client/src/Components/RegisterPageComponents/Stepper/BodyStepper.jsx
  client/src/Components/RegisterPageComponents/Stepper/HeaderStepper.jsx
  client/src/Components/RegisterPageComponents/Stepper/StepperLayout.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/StepOneComponent.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/StepThreeComponent.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/StepTwoComponent.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/index.js
  client/src/Components/RegisterPageComponents/index.js
  client/src/Components/index.js
  client/src/Pages/RegisterGym.jsx
  client/src/Store/Slices/StepperSlice.js
  client/src/Store/Slices/index.js
  client/src/Store/index.js
  client/src/app.css
Labels: Approved, FrontEnd

#67 Get data from API and convert the Search Page to be dynamic
  client/src/App.js
  client/src/Components/SearchPageComponents/CardResultFilter/Card.jsx
  client/src/Components/SearchPageComponents/CardResultFilter/LoadingCard.jsx
  client/src/Components/SearchPageComponents/CardResultFilter/index.jsx
  client/src/Components/SearchPageComponents/CardResultFilter/style.css
  client/src/Components/SearchPageComponents/Filter/index.jsx
  client/src/Components/SearchPageComponents/FilterSide/gymdata.jsx
  client/src/Components/SearchPageComponents/FilterSide/index.jsx
  client/src/Components/SearchPageComponents/FilterSide/style.css
  client/src/Pages/SearchGym.jsx
Labels: Done, FrontEnd, BackEnd

#77 Start creating step contact information
  client/package-lock.json
  client/package.json
  client/src/Components/RegisterPageComponents/Stepper/BodyStepper.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/ContactInformation.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/StepTwoComponent.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/index.js
  client/src/Components/RegisterPageComponents/Stepper/Steps/style.css
  client/src/Services/Cities.json
  client/src/Theme.js
Labels: Awaiting Review, FrontEnd

#79 Edit Fake Data
  client/src/Components/SearchPageComponents/FilterSide/gymdata.jsx
  server/database/fakeData/gyms.json
  server/database/models/gyms.ts
  test/filterGymsRoute.test.ts
Labels: Approved, BackEnd

#84 First form singup gym
  client/src/Components/RegisterPageComponents/Stepper/BodyStepper.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/LoginInformation.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/StepOneComponent.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/index.js
  client/src/Components/RegisterPageComponents/Stepper/Steps/style.css
  client/src/utils/convertToBase64.js
  client/src/utils/index.js
Labels: Awaiting Review, FrontEnd

#82 Create Step Three Form register
  client/src/Components/RegisterPageComponents/Stepper/BodyStepper.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/DetailsComponent.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/StepThreeComponent.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/index.js
  client/src/Services/features.json
  client/src/Services/genders.json
  services/features.json
Labels: Approved, FrontEnd

#91 Fix Eslint Issues
  client/src/Components/RegisterPageComponents/Stepper/BodyStepper.jsx
  client/src/Components/RegisterPageComponents/Stepper/Steps/index.js
Labels: Awaiting Review, FrontEnd

#87 Create API for register gym and test it
  .eslintrc.json
  .github/workflows/node.js.yml
  example.env
  package-lock.json
  package.json
  server/controllers/auth/gymRegister.ts
  server/controllers/auth/index.ts
  server/controllers/gyms/getFilteredGyms.ts
  server/controllers/index.ts
  server/database/fakeData/gyms.json
  server/database/models/gyms.ts
  server/routes/gyms.ts
  server/utils/aws/index.ts
  server/utils/index.ts
  server/utils/types.ts
  server/utils/validation/gymRegisterSchema.ts
  server/utils/validation/index.ts
  test/authGymsRoute.test.ts
Labels: Awaiting Review, BackEnd

#94 Frontend Restructure File Inside Folder Components
  client/src/Components/DashboardPage/Header/index.jsx
  client/src/Components/DashboardPage/SideBar/index.jsx
  client/src/Components/DashboardPage/index.js
  client/src/Components/HomePage/GymCard/index.jsx
  client/src/Components/HomePage/GymCard/style.css
  client/src/Components/HomePage/JoinUs/index.jsx
  client/src/Components/HomePage/JoinUs/style.css
  client/src/Components/HomePage/OfferForYou/index.jsx
  client/src/Components/HomePage/OfferForYou/style.css
  client/src/Components/HomePage/Slider/Style.css
  client/src/Components/HomePage/Slider/index.jsx
  client/src/Components/HomePage/TopGymCards/LoadingCard.jsx
  client/src/Components/HomePage/TopGymCards/index.jsx
  client/src/Components/HomePage/TopGymCards/style.css
  client/src/Components/HomePage/index.js
  client/src/Components/Layout/Footer/index.jsx
  client/src/Components/Layout/Footer/style.css
  client/src/Components/Layout/Navbar/index.jsx
  client/src/Components/Layout/Navbar/style.css
  client/src/Components/Layout/index.js
  client/src/Components/Navbar/index.jsx
  client/src/Components/RegisterPage/Stepper/BodyStepper.jsx
  client/src/Components/RegisterPage/Stepper/HeaderStepper.jsx
  client/src/Components/RegisterPage/Stepper/StepperLayout.jsx
  client/src/Components/RegisterPage/Stepper/Steps/ContactInformation.jsx
  client/src/Components/RegisterPage/Stepper/Steps/DetailsComponent.jsx
  client/src/Components/RegisterPage/Stepper/Steps/LoginInformation.jsx
  client/src/Components/RegisterPage/Stepper/Steps/index.js
  client/src/Components/RegisterPage/Stepper/Steps/style.css
  client/src/Components/RegisterPage/index.js
  client/src/Components/SearchPage/CardResultFilter/Card.jsx
  client/src/Components/SearchPage/CardResultFilter/LoadingCard.jsx
  client/src/Components/SearchPage/CardResultFilter/index.jsx
  client/src/Components/SearchPage/CardResultFilter/style.css
  client/src/Components/SearchPage/Filter/index.jsx
  client/src/Components/SearchPage/Filter/style.css
  client/src/Components/SearchPage/FilterSide/gymdata.jsx
  client/src/Components/SearchPage/FilterSide/index.jsx
  client/src/Components/SearchPage/FilterSide/style.css
  client/src/Components/SearchPage/index.js
  client/src/Components/SingleGym/GymImages/index.jsx
  client/src/Components/SingleGym/GymImages/style.css
  client/src/Components/SingleGym/GymProfile/index.jsx
  client/src/Components/SingleGym/GymProfile/style.css
  client/src/Components/SingleGym/GymReviews/Review.jsx
  client/src/Components/SingleGym/GymReviews/index.jsx
  client/src/Components/SingleGym/GymReviews/style.css
  client/src/Components/SingleGym/index.js
  client/src/Components/index.js
  client/src/Layouts/Home.jsx
  client/src/Pages/Gym.jsx
  client/src/Pages/HomePage.jsx
  client/src/Pages/ProfileGym.jsx
  client/src/Pages/ReviewsGymPage.jsx
  client/src/Pages/SubscriberGymPage.jsx
Labels: Awaiting Review, FrontEnd

#89 Login gym api
  server/controllers/auth/gymLogin.ts
  server/controllers/auth/index.ts
  server/controllers/index.ts
  server/routes/gyms.ts
  server/utils/index.ts
  server/utils/validation/gymLoginSchema.ts
  server/utils/validation/index.ts
  test/loginGymRoute.test.ts
Labels: Approved, BackEnd

#97 Create Login page
  client/src/Components/LoginPage/index.jsx
  client/src/Components/index.js
  client/src/Pages/LoginGym.jsx
Labels: Awaiting Review, FrontEnd

#98 FrontEnd Create Page Update Profile Gym
  client/src/App.js
  client/src/Components/DashboardPage/UpdateProfile/index.jsx
  client/src/Components/DashboardPage/UpdateProfile/style.css
  client/src/Components/DashboardPage/index.js
  client/src/Components/RegisterPage/Stepper/BodyStepper.jsx
  client/src/Components/RegisterPage/Stepper/Steps/LoginInformation.jsx
  client/src/Components/RegisterPage/Stepper/Steps/style.css
  client/src/Components/index.js
  client/src/Layouts/Dashboard.jsx
  client/src/Pages/GymProfile.jsx
  client/src/Pages/SingleGym.jsx
  client/src/Pages/index.js
  client/src/Services/genders.json
  client/src/Services/index.js
Labels: Approved, FrontEnd

#99 Create API For Edit Gym and test it
  .github/workflows/node.js.yml
  example.env
  server/controllers/auth/gymRegister.ts
  server/controllers/gym/editGym.ts
  server/controllers/gym/index.ts
  server/controllers/index.ts
  server/error/serverError.ts
  server/routes/gyms.ts
  server/utils/aws/index.ts
  server/utils/index.ts
  server/utils/types.ts
  server/utils/validation/gymEditSchema.ts
  server/utils/validation/index.ts
  test/editGymsRoute.test.ts
Labels: Awaiting Review, BackEnd

#103 Update api single gym and make component update gym dynamic
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/DashboardPage/Header/index.jsx
  client/src/Components/DashboardPage/UpdateProfile/LoadingForm.jsx
  client/src/Components/DashboardPage/UpdateProfile/index.jsx
  client/src/Components/DashboardPage/UpdateProfile/style.css
  client/src/Layouts/Dashboard.jsx
  example.env
  package-lock.json
  package.json
  server/app.ts
  server/controllers/gym/getGym.ts
Labels: Approved, FrontEnd, BackEnd

#106 Create API For Post Images Gym
  server/controllers/gym/index.ts
  server/controllers/gym/postImage.ts
  server/controllers/index.ts
  server/routes/gym.ts
  server/routes/index.ts
  server/utils/index.ts
  server/utils/validation/gymImageSchema.ts
  server/utils/validation/index.ts
Labels: Awaiting Review, BackEnd

#111 add deploy file
  .github/workflows/deploy.js.yml
Labels: Awaiting Review

#109 Create navbar to home page and style it
  client/src/Components/DashboardPage/SideBar/index.jsx
  client/src/Components/Layout/Footer/index.jsx
  client/src/Components/Layout/Navbar/CardInputSearch.jsx
  client/src/Components/Layout/Navbar/index.jsx
  client/src/Components/Layout/Navbar/style.css
  client/src/Store/Slices/checkAuthSlice.js
  client/src/app.css
Labels: Awaiting Review, FrontEnd

#110 Upload images
  client/src/App.js
  client/src/Components/DashboardPage/SideBar/index.jsx
  client/src/Components/DashboardPage/UploadImages/LoadingForm.jsx
  client/src/Components/DashboardPage/UploadImages/index.jsx
  client/src/Components/DashboardPage/UploadImages/style.css
  client/src/Components/DashboardPage/index.js
  client/src/Components/index.js
  client/src/Pages/ImagesGymPage.jsx
  client/src/Pages/index.js
Labels: Done, FrontEnd

#112 Deployment
  client/package-lock.json
  client/package.json
  client/src/Components/RegisterPage/Stepper/Steps/ContactInformation.jsx
  client/src/Components/RegisterPage/Stepper/Steps/DetailsComponent.jsx
  client/src/Services/cities.js
  client/src/Services/features.js
  client/src/Services/genders.js
  client/src/Services/index.js
  package.json
  server/database/config/connection.ts
Labels: Awaiting Review

#108 Make gym register page dynamic
  client/package-lock.json
  client/src/Components/DashboardPage/UpdateProfile/style.css
  client/src/Components/DashboardPage/UploadImages/style.css
  client/src/Components/LoginPage/index.jsx
  client/src/Components/RegisterPage/Stepper/BodyStepper.jsx
  client/src/Components/RegisterPage/Stepper/StepperLayout.jsx
  client/src/Components/RegisterPage/Stepper/Steps/ContactInformation.jsx
  client/src/Components/RegisterPage/Stepper/Steps/DetailsComponent.jsx
  client/src/Components/RegisterPage/Stepper/Steps/LoginInformation.jsx
  client/src/Components/RegisterPage/Stepper/Steps/style.css
  client/src/Components/RegisterPage/registerSchema.js
  client/src/Pages/RegisterGym.jsx
  package-lock.json
  server/app.ts
  server/utils/validation/gymRegisterSchema.ts
Labels: Awaiting Review, FrontEnd, BackEnd

#115 Edit database
  server/controllers/gym/editGym.ts
  server/controllers/gym/getGym.ts
  server/controllers/gym/postImage.ts
  server/database/fakeData/index.ts
  server/database/fakeData/reviews.json
  server/database/fakeData/subscriptions.json
  server/database/fakeData/users.json
  server/database/models/index.ts
  server/database/models/reviews.ts
  server/database/models/subscription.ts
  server/database/models/users.ts
Labels: Approved, BackEnd

#118 Create api post subscription and test it
  server/controllers/index.ts
  server/controllers/subscription/addSubscription.ts
  server/controllers/subscription/index.ts
  server/routes/index.ts
  server/routes/subscription.ts
  server/utils/index.ts
  server/utils/validation/addSubscriptionSchema.ts
  server/utils/validation/index.ts
  test/addSubscription.test.ts
Labels: Awaiting Review, BackEnd

#119 Delete image api
  server/controllers/gym/deleteImage.ts
  server/controllers/gym/getGym.ts
  server/controllers/gym/index.ts
  server/controllers/index.ts
  server/database/models/images.ts
  server/routes/gym.ts
  server/utils/index.ts
  server/utils/types.ts
Labels: Approved, BackEnd

#125 Create protected route in frontend
  client/src/App.js
  client/src/Pages/Login.jsx
  client/src/Pages/Register.jsx
  client/src/Pages/index.js
  client/src/middleware/ProtectedRoutes.jsx
  client/src/middleware/RegisteredGymRoutes.jsx
  client/src/middleware/index.js
Labels: Approved, FrontEnd

#124 Create API For Get Subscription gym
  server/controllers/gym/getSubscription.ts
  server/controllers/gym/index.ts
  server/controllers/index.ts
  server/routes/gym.ts
Labels: Approved, BackEnd

#127 Front End, Fix Login Page
  client/src/Components/LoginPage/index.jsx
  client/src/Components/RegisterPage/Stepper/Steps/DetailsComponent.jsx
  client/src/Pages/LoginGym.jsx
Labels: Awaiting Review, FrontEnd

#126 Fix bug in filter controller and fix cookies http only backend
  server/controllers/auth/gymLogin.ts
  server/controllers/auth/gymRegister.ts
  server/controllers/gyms/getFilteredGyms.ts
Labels: Approved, BackEnd

#134 Create add review
  server/controllers/gyms/addReview.ts
  server/controllers/gyms/index.ts
  server/controllers/index.ts
  server/database/fakeData/subscriptions.json
  server/database/models/reviews.ts
  server/routes/gym.ts
  server/routes/gyms.ts
  server/utils/index.ts
  server/utils/validation/addReviewSchema.ts
  server/utils/validation/index.ts
  test/addReview.test.ts
Labels: Approved, BackEnd

#133 Create subscription table
  client/src/Components/DashboardPage/Subscriptions/EnhancedTableHead.jsx
  client/src/Components/DashboardPage/Subscriptions/EnhancedTableRow.jsx
  client/src/Components/DashboardPage/Subscriptions/EnhancedTableToolbar.jsx
  client/src/Components/DashboardPage/Subscriptions/index.jsx
  client/src/Pages/SubscriberGymPage.jsx
  client/src/Store/Services/index.js
  client/src/Store/Services/subscription.js
  client/src/Store/index.js
Labels: Awaiting Review, FrontEnd

#137 [FrontEnd] handle activate user
  client/src/Components/DashboardPage/Subscriptions/EnhancedTableRow.jsx
Labels: Approved, FrontEnd

#140 Update gym profile
  client/src/Components/SingleGym/GymImages/index.jsx
  client/src/Components/SingleGym/GymProfile/index.jsx
  client/src/Components/SingleGym/GymProfile/style.css
  client/src/Components/SingleGym/GymReviews/index.jsx
  client/src/Components/SingleGym/GymReviews/style.css
Labels: Awaiting Review, FrontEnd

#143 Update header dashboard and update not found page
  client/src/App.js
  client/src/Components/DashboardPage/Header/index.jsx
  client/src/Components/DashboardPage/Header/style.css
  client/src/Components/DashboardPage/SideBar/index.jsx
  client/src/Components/DashboardPage/SideBar/style.css
  client/src/Components/Layout/Navbar/style.css
  client/src/Pages/NotFound.jsx
  client/src/Pages/SingleGym.jsx
  client/src/app.css
Labels: Approved, FrontEnd

#145 General points to fix
  client/src/Components/HomePage/GymCard/index.jsx
  client/src/Components/HomePage/OfferForYou/index.jsx
  client/src/Components/SearchPage/CardResultFilter/Card.jsx
  client/src/Components/SearchPage/CardResultFilter/LoadingCard.jsx
  client/src/Components/SearchPage/FilterSide/gymdata.jsx
  client/src/Components/SearchPage/FilterSide/index.jsx
  client/src/Components/SingleGym/Modal/index.jsx
  server/utils/validation/filterValidation.ts
Labels: Awaiting Review, bug

#147 Setup email to send reset password
  example.env
  package-lock.json
  package.json
  server/utils/email/index.ts
  server/utils/email/templates/forgetPasswordTemp.ts
  server/utils/index.ts
Labels: Approved, BackEnd

#149 Add review
  client/src/Components/SingleGym/GymReviews/index.jsx
  client/src/Components/SingleGym/Modal/index.jsx
  client/src/Pages/SingleGym.jsx
Labels: Awaiting Review, FrontEnd

#151 Create Api forget password and reset it
  server/controllers/auth/forgetPassword.ts
  server/controllers/auth/index.ts
  server/controllers/auth/resetPassword.ts
  server/controllers/index.ts
  server/routes/gyms.ts
  server/utils/email/templates/forgetPasswordTemp.ts
  server/utils/index.ts
  server/utils/jwt.ts
  server/utils/validation/forgetPasswordSchema.ts
  server/utils/validation/gymLoginSchema.ts
  server/utils/validation/gymRegisterSchema.ts
  server/utils/validation/index.ts
  server/utils/validation/resetPasswordSchema.ts
Labels: Awaiting Review, BackEnd

#152 Forget password
  client/src/App.js
  client/src/Components/LoginPage/EmailInput.jsx
  client/src/Components/LoginPage/ForgetPassword/index.jsx
  client/src/Components/LoginPage/PasswordInput.jsx
  client/src/Components/LoginPage/RestPassword/index.jsx
  client/src/Components/LoginPage/index.jsx
  client/src/Components/SingleGym/Modal/index.jsx
  client/src/Pages/ForgetPassword.jsx
  client/src/Pages/LoginGym.jsx
  client/src/Pages/RestPassword.jsx
Labels: Approved, FrontEnd

#154 Handle Forget password
  client/src/Components/LoginPage/ForgetPassword/index.jsx
  client/src/Components/LoginPage/index.jsx
  client/src/Pages/ForgetPassword.jsx
Labels: Awaiting Review, FrontEnd

#159 Fix footer style and put it in bottom
  client/src/Components/Layout/Footer/index.jsx
  client/src/Layouts/Home.jsx
  client/src/app.css
Labels: Approved, FrontEnd

#161 Fix fack data in server
  client/src/Components/DashboardPage/SideBar/index.jsx
  client/src/Components/HomePage/Slider/Style.css
  client/src/Components/SearchPage/CardResultFilter/Card.jsx
  client/src/Components/SearchPage/CardResultFilter/index.jsx
  server/database/fakeData/gyms.json
  server/database/fakeData/images.json
Labels: Approved, BackEnd

#157 Create README
  README.md
Labels: In Progress, documentation, readme
