Repository GSG-G11/Fitness-house, pull requests merged in 2022-04, with the labels that each got.

#2 setup husky
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.js
  package-lock.json
  package.json
Labels: Approved

#6 create folder and file structure for server
  .eslintrc.json
  .gitignore
  commitlint.config.js
  example.env
  package-lock.json
  package.json
  server/app.ts
  server/controllers/index.ts
  server/database/config/build.sql
  server/database/config/build.ts
  server/database/config/connection.ts
  server/database/fakeData/index.ts
  server/database/models/index.ts
  server/index.ts
  server/middlewares/index.ts
  server/routes/index.ts
  server/test/database.test.ts
  server/test/routes.test.ts
  server/utils/CustomError.ts
  server/utils/index.ts
  server/utils/jwt.ts
  server/utils/validation/index.ts
  tsconfig.json
Labels: Done

#10 edit file structure
  .eslintrc.json
  package.json
  server/test/database.test.ts
  server/test/routes.test.ts
  test/routes.test.js
Labels: Awaiting Review

#14 Database Connection and configs
  .eslintrc.json
  client/.eslintrc.json
  commitlint.config.js
  package-lock.json
  package.json
  server/app.ts
  server/database/config/build.sql
  server/database/config/connection.ts
  server/database/models/index.ts
Labels: request changes

#13 Initialise react routes and create layout folder
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/Components/Navbar/index.js
  client/src/Components/Navbar/index.jsx
  client/src/Components/index.jsx
  client/src/Pages/Gym.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/LoginGym.jsx
  client/src/Pages/NotFound.jsx
  client/src/Pages/ProfileGym.jsx
  client/src/Pages/Register.jsx
  client/src/Pages/RegisterGym.jsx
  client/src/Pages/SearchGym.jsx
  client/src/Pages/index.js
  client/src/app.css
  client/src/index.js
  client/src/layouts/Dashboard.jsx
  client/src/layouts/Home.jsx
  client/src/layouts/index.jsx
Labels: Done

#17 Create User Model
  server/database/models/index.ts
  server/database/models/user.ts
Labels: Awaiting Review

#18 Create gym and image model in server
  server/database/models/gyms.ts
  server/database/models/images.ts
  server/database/models/index.ts
Labels: Done

#21 create subscription and reviews model
  server/database/models/index.ts
  server/database/models/reviews.ts
  server/database/models/subscription.ts
Labels: Done
